// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRFIMfQxbE1q1nttSvEuVn2C-iokhYV0I',
    appId: '1:633321044450:web:2edb7a98afa983f8c3e1bb',
    messagingSenderId: '633321044450',
    projectId: 'my-task-manager-dbf5b',
    authDomain: 'my-task-manager-dbf5b.firebaseapp.com',
    storageBucket: 'my-task-manager-dbf5b.firebasestorage.app',
    measurementId: 'G-D8H0XTE2Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWv4gJMZ_wLO0fzgHJBt0-Hdo5sfqpUXc',
    appId: '1:633321044450:android:69567f764349bce2c3e1bb',
    messagingSenderId: '633321044450',
    projectId: 'my-task-manager-dbf5b',
    storageBucket: 'my-task-manager-dbf5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxXvmY-toZ9TaXmcdiOl6un1ZWKMd2omY',
    appId: '1:633321044450:ios:49d6a3afcaa5566dc3e1bb',
    messagingSenderId: '633321044450',
    projectId: 'my-task-manager-dbf5b',
    storageBucket: 'my-task-manager-dbf5b.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxXvmY-toZ9TaXmcdiOl6un1ZWKMd2omY',
    appId: '1:633321044450:ios:49d6a3afcaa5566dc3e1bb',
    messagingSenderId: '633321044450',
    projectId: 'my-task-manager-dbf5b',
    storageBucket: 'my-task-manager-dbf5b.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRFIMfQxbE1q1nttSvEuVn2C-iokhYV0I',
    appId: '1:633321044450:web:6c414761de8b44f9c3e1bb',
    messagingSenderId: '633321044450',
    projectId: 'my-task-manager-dbf5b',
    authDomain: 'my-task-manager-dbf5b.firebaseapp.com',
    storageBucket: 'my-task-manager-dbf5b.firebasestorage.app',
    measurementId: 'G-5XJ3G917EE',
  );
}
